#assignment 2 make
default: main.c main.h workQueues.c utils.c consumer.c producer.c stats.c tands.c
	gcc main.c -o prodcon -pthread -O

clean:#Remove executable
	rm prodcon

cc: clearScrn default#clear screen the run default

clearScrn:#clear screen
	clear