--Question 2
.print Question 2 - dchu
SELECT *
FROM (SELECT s.NAME,count(*)
FROM SALESREPS as s, ORDERS as o
WHERE s.EMP_ID = o.REP
GROUP by s.EMP_ID)

UNION ALL

SELECT *
FROM (SELECT s.NAME,NULL
FROM SALESREPS as s
WHERE s.EMP_ID NOT IN (SELECT REP FROM ORDERS)
GROUP by s.EMP_ID);