PRAGMA foreign_keys = ON;

--DROP TABLE ORDERS;
--DROP TABLE PRODUCTS;
--DROP TABLE CUSTOMERS;
--DROP TABLE SALESREPS;
--DROP TABLE OFFICES;

CREATE TABLE OFFICES
(
 OFFICE   INTEGER	PRIMARY KEY,
 CITY     VARCHAR(20)	NOT NULL,
 REGION   VARCHAR(15)	NOT NULL,
 TARGET   NUMBER 	NOT NULL,
 SALES    NUMBER	NOT NULL
);

CREATE TABLE PRODUCTS
(
 PRODUCT_ID       CHAR(10)      PRIMARY KEY,
 DESCRIPTION      VARCHAR(50),
 PRICE            NUMBER	NOT NULL,
 QTY_ON_HAND   	  INTEGER	NOT NULL
);

CREATE TABLE SALESREPS
(
 EMP_ID	   	INTEGER		PRIMARY KEY,
 NAME	   	VARCHAR(25)	NOT NULL,
 REP_OFFICE   	INTEGER  	NOT NULL,
 HIRE_YEAR	INTEGER		NOT NULL,
 MANAGER	NUMBER 		NOT NULL,
 QUOTA	   	INTEGER,
 SALES	   	NUMBER		NOT NULL,
 FOREIGN KEY(REP_OFFICE) REFERENCES OFFICES ON DELETE  CASCADE,
 FOREIGN KEY(MANAGER)   REFERENCES SALESREPS ON DELETE SET NULL
);

CREATE TABLE CUSTOMERS
(
 CUST_NUM	INTEGER 	PRIMARY KEY,
 COMPANY	VARCHAR(20),
 CUST_REP	INTEGER 	NOT NULL,
 CREDIT_LIMIT   NUMBER		NOT NULL,
 FOREIGN KEY(CUST_REP) REFERENCES SALESREPS ON DELETE SET NULL
); 

CREATE TABLE ORDERS
(
 ORDER_NUM	INTEGER		PRIMARY KEY,
 CUST		INTEGER 	NOT NULL,
 REP		INTEGER		NOT NULL,
 PRODUCT	CHAR(10)	NOT NULL,
 QTY		INTEGER		NOT NULL,
 FOREIGN KEY(CUST) REFERENCES CUSTOMERS ON DELETE CASCADE,
 FOREIGN KEY(REP) REFERENCES SALESREPS ON DELETE SET NULL,
 FOREIGN KEY(PRODUCT) REFERENCES PRODUCTS ON DELETE SET NULL 
);

